# Generated by Django 5.2.3 on 2025-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('strategy', models.CharField(max_length=100)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('pnl', models.FloatField()),
                ('cumulative_equity', models.FloatField()),
            ],
        ),
    ]
